//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\VS_NX\WireBuilder_ver_0.1\NXDialog\WBDialog_v10.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: Asus
//              Version: NX 8.5
//              Date: 12-04-2014  (Format: mm-dd-yyyy)
//              Time: 20:41
//
//==============================================================================

#ifndef WBDIALOG_V10_H_INCLUDED
#define WBDIALOG_V10_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------

 //+
#include"WireBuilder.h"
#include<Windows.h>
#include<WinBase.h>
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_ListBox.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_LinearDimension.hxx>
#include <NXOpen/BlockStyler_Toggle.hxx>
#include <NXOpen/BlockStyler_ExpressionBlock.hxx>
#include <NXOpen/BlockStyler_FaceCollector.hxx>
#include <NXOpen/BlockStyler_ReverseDirection.hxx>
#include <NXOpen/BlockStyler_Button.hxx>
#include <NXOpen/BlockStyler_SpecifyCSYS.hxx>
#include<NXOpen\TaggedObject.hxx>
#include<sstream>
//------------------------------------------------------------------------------
//Bit Option for Property: SnapPointTypesOnByDefault
//------------------------------------------------------------------------------
#define          SnapPointTypesOnByDefault_UserDefined (1 << 0);
#define             SnapPointTypesOnByDefault_Inferred (1 << 1);
#define       SnapPointTypesOnByDefault_ScreenPosition (1 << 2);
#define             SnapPointTypesOnByDefault_EndPoint (1 << 3);
#define             SnapPointTypesOnByDefault_MidPoint (1 << 4);
#define         SnapPointTypesOnByDefault_ControlPoint (1 << 5);
#define         SnapPointTypesOnByDefault_Intersection (1 << 6);
#define            SnapPointTypesOnByDefault_ArcCenter (1 << 7);
#define        SnapPointTypesOnByDefault_QuadrantPoint (1 << 8);
#define        SnapPointTypesOnByDefault_ExistingPoint (1 << 9);
#define         SnapPointTypesOnByDefault_PointonCurve (1 <<10);
#define       SnapPointTypesOnByDefault_PointonSurface (1 <<11);
#define     SnapPointTypesOnByDefault_PointConstructor (1 <<12);
#define SnapPointTypesOnByDefault_TwocurveIntersection (1 <<13);
#define         SnapPointTypesOnByDefault_TangentPoint (1 <<14);
#define                SnapPointTypesOnByDefault_Poles (1 <<15);
#define     SnapPointTypesOnByDefault_BoundedGridPoint (1 <<16);
//------------------------------------------------------------------------------
//Bit Option for Property: EntityType
//------------------------------------------------------------------------------
#define                          EntityType_AllowFaces (1 << 4);
#define                         EntityType_AllowDatums (1 << 5);
#define                         EntityType_AllowBodies (1 << 6);
//------------------------------------------------------------------------------
//Bit Option for Property: FaceRules
//------------------------------------------------------------------------------
#define                           FaceRules_SingleFace (1 << 0);
#define                          FaceRules_RegionFaces (1 << 1);
#define                         FaceRules_TangentFaces (1 << 2);
#define                   FaceRules_TangentRegionFaces (1 << 3);
#define                            FaceRules_BodyFaces (1 << 4);
#define                         FaceRules_FeatureFaces (1 << 5);
#define                        FaceRules_AdjacentFaces (1 << 6);
#define                  FaceRules_ConnectedBlendFaces (1 << 7);
#define                        FaceRules_AllBlendFaces (1 << 8);
#define                             FaceRules_RibFaces (1 << 9);
#define                            FaceRules_SlotFaces (1 <<10);
#define                   FaceRules_BossandPocketFaces (1 <<11);
#define                       FaceRules_MergedRibFaces (1 <<12);
#define                  FaceRules_RegionBoundaryFaces (1 <<13);
#define                 FaceRules_FaceandAdjacentFaces (1 <<14);
//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport WBDialog_v10
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
	Part* workPart;//+
    WBDialog_v10();
    ~WBDialog_v10();
    int Show();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the WBDialog_v10.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);
    
private:
	//+
	bool buttonHelixPressed;
	int counter;
	int counterAdditionHole;
	bool isAddBelow;
	bool isNeedSolidBody;
	std::vector<NXString> listOfItems;
	int whatIsSelected;
	size_t valueOfHoles;
	std::vector<TaggedObject*> lastSelectedHoles;
	std::vector<TaggedObject*>::iterator iter;
	//+

	WireBuilder Wire; // онтейнерный класс дл€ всех методов и классов необходимых дл€ построени€ проволоки

    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group1;// Block type: Group
    NXOpen::BlockStyler::LinearDimension* exprDiameter;// Block type: Linear Dim
    NXOpen::BlockStyler::Toggle* isSpline3;// Block type: Toggle
    NXOpen::BlockStyler::Group* group2;// Block type: Group
    NXOpen::BlockStyler::Toggle* isSolid;// Block type: Toggle
    NXOpen::BlockStyler::LinearDimension* DiameterHelix;// Block type: Linear Dim
    NXOpen::BlockStyler::LinearDimension* LengthHelix;// Block type: Linear Dim
    NXOpen::BlockStyler::LinearDimension* PitchHelix;// Block type: Linear Dim
    NXOpen::BlockStyler::ExpressionBlock* tangent;// Block type: Expression
    NXOpen::BlockStyler::Group* group0;// Block type: Group
    NXOpen::BlockStyler::FaceCollector* FaceSelect;// Block type: Face Collector
    NXOpen::BlockStyler::ReverseDirection* IsReversed;// Block type: Reverse Direction
    NXOpen::BlockStyler::ListBox* ListOfHoles;// Block type: List Box
    NXOpen::BlockStyler::Button* deleteButton;// Block type: Button
	NXOpen::BlockStyler::Toggle* AddBelow;// Block type: Toggle
    NXOpen::BlockStyler::Group* group;// Block type: Group
    NXOpen::BlockStyler::Button* buttonHelix;// Block type: Button
    NXOpen::BlockStyler::SpecifyCSYS* HelixCoordinateSystem;// Block type: Specify Csys
    NXOpen::BlockStyler::Group* group4;// Block type: Group
    NXOpen::BlockStyler::Button* buttonShow;// Block type: Button
    NXOpen::BlockStyler::Button* ComeBack;// Block type: Button
    NXOpen::BlockStyler::Group* group3;// Block type: Group
    NXOpen::BlockStyler::Button* buttonSeal;// Block type: Button
    NXOpen::BlockStyler::ExpressionBlock* lengthOUT;// Block type: Expression
    NXOpen::BlockStyler::ExpressionBlock* widthOUT;// Block type: Expression
    
};
#endif //WBDIALOG_V10_H_INCLUDED
